server:
  port: 8761
spring:
  application:
    name: service-registry
#  cloud:
#    config:
#      uri: http://localhost:8888
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
---
spring:
#  cloud:
#    config:
#      uri: http://configserver:8888
  config:
    activate:
      on-profile: docker
