server:
  port: 8002
logging:
  level:
    org:
      springframework:
        security: DEBUG
###
#   Database Settings
###
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
